### ISSUE TITLE
How do you manage notifications from GitHub?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#813]
Several people have turned off GitHub notifications entirely because of the flood of messages from our various repositories.  How do *you* manage it?  What do you pay attention to, and what would you *like* to pay attention to?

**Comment by jiffyclub** [comment]
Now that we've split the repositories it's much easier to turn notifications on and off per-topic. For example, I don't get notifications from any of the R repositories now. That was a great benefit of the split, even though we did it for other reasons. Here's more on "unwatching" a repository: https://help.github.com/articles/unwatching-repositories/

**Comment by jiffyclub** [comment]
The lesson-template and workshop-template repos have been generating a ton of emails, but I don't expect that to last forever.

**Comment by keipertk** [comment]
I use Gmail which has an option to set categories for email i.e. social, promotions, updates, etc. All messages I receive from Github are automatically sent to one email category which is separate from my primary email. This doesn't help limit the number of emails I receive, but I don't receive notifications like I do for messages which are categorized into "primary".

**Comment by lgatto** [comment]
I am `ignoring` repositories I am very unlikely every going to contribute to, `not watching` those that are of interest but not important at the moment and `watch` only the most relevant ones.

**Comment by moorepants** [comment]
I simply turn off everything unless I get an @mention. Then it is up to people to ping you explicitly if they want your attention via email.

**Comment by cboettig** [comment]
Github's notification system is really friendly and fine grained. Like others have mentioned, I start by going to https://github.com/watching and "unwatching" everything you don't care about.  

Then go to https://github.com/settings/notifications and consider one of the following strategies:

- Uncheck "automatic watching" so you're not signed up to watch stuff just because you've been given access to the git repo.  

For even fewer emails: 

- Uncheck 'email notifications' under "watching".  (e.g. only be emailed when you are mentioned explicitly, but still be able to use the web notifications otherwise for all repositories you are watching).  (Given this setting it is a good idea to explicitly mention anyone like @gvwilson if you want to make sure they see the thread)

Other options if you like web-based platforms are to integrate your repositories into a system like slack, or even just rely on the github notifications web interface to catch up with what's going on (once you've unwatched stuff you don't care about so it's not overwhelming).

**Comment by bandyopa** [comment]
I use filters in Gmail to redirect to a "label. Works fine. I can go and have a look at one go and see if there's anything that I need to do.

**Comment by drlabratory** [comment]
One other trick is github can do custom routing by group (bottom of https://github.com/settings/notifications). Add to that gmail's ability to add whatever you want to your address using a plus sign, and you could route all swc github notifications by sending them to first.last+swc@gmail.com, then use a custom filter on the gmail side.

**Comment by tpoisot** [comment]
I will most likely fine-tune things. Some repos where I feel like I can contribute, I will keep on watching. Others will be muted.

**Comment by noamross** [comment]
I fine tune but do it at the inbox level.  I use Google Inbox, their new Gmail interface, and it is very good at letting you set the desired frequency of attention you pay to a category of messages.

**Comment by wking** [comment]
On Wed, Feb 11, 2015 at 06:25:56PM -0800, bandyopa wrote:
> I use filters in Gmail to redirect to a label…

I like the “high email volume, but good filtering to only *show* you
what you care about” approach.  For folks who want to self-host, I've
really liked notmuch [1] for tagging and searching mail locally.  It's
easy to automatically tag incoming messages based on the sender or
subject, and either automatically remove a given category from your
inbox [2] or hide futher messages in threads you've manually muted
[3].

[1]: http://notmuchmail.org/
[2]: http://notmuchmail.org/initial_tagging/
[3]: http://notmuchmail.org/pipermail/notmuch/2014/016906.html

**Comment by jiffyclub** [comment]
You can also selectively unsubscribe from busy issues or pull requests like this one, so even if you want to watch a repo, you can stop getting email about an issue you don't care about. The "Unsubscribe" button is on the right under labels and assignee.
![screen shot 2015-02-12 at 10 10 01 am](https://cloud.githubusercontent.com/assets/920492/6173808/8056f6d6-b29f-11e4-9f5d-0e6b71beca0f.png)
