### ISSUE TITLE
How to make a workshop Etherpad

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/site#935]
The [lead instructor checklist](https://github.com/swcarpentry/site/blob/master/workshops/checklists/lead_instructor.html) says we need to create a workshop etherpad, but doesn't give any instruction about how to do that. I personally have no idea.

**Comment by r-gaia-cs** [comment]
If the workshop ID is `2020-01-01-university` the etherpad link should be http://etherpad.mozilla.org/2020-01-01-university. The first time that anyone access the etherpad link it will be create.

**Comment by gvwilson** [comment]
I'll add instructions - thanks for the catch.

**Comment by chendaniely** [comment]
I've been using  https://swcarpentry.etherpad.mozilla.org/yyyy-mm-dd-university
does it matter if we use the swcarpentry subdomain (is that what it's called?) or not?

**Comment by gvwilson** [comment]
Doesn't matter - I usually create them under 
etherpad.mozilla.org/something-or-other.

**Comment by embray** [comment]
Indeed, I set up https://swcarpentry.etherpad.mozilla.org some time ago, and have always used it to host workshop etherpads.   Let me know if you need me to add you as an administrator (though I don't think it's necessary to create a new pad there).

One thing that I would like to see called out in the instructions is that students *do not need an account* on etherpad.org in order to view and edit the public etherpads created for workshops.  Although it's been less of a problem lately I still occasionally get one or two e-mails of account requests whenever there's a workshop going on.

**Comment by gvwilson** [comment]
Relocated to https://github.com/swcarpentry/website/issues/99
