### ISSUE TITLE
Create a help@software-carpentry.org address

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#947]
So that people who want help can get it - should be a broadcast list to a small set of volunteers.

**Comment by wking** [comment]
On Tue, Apr 21, 2015 at 11:24:32AM -0700, Greg Wilson wrote:
> So that people who want help can get it - should be a broadcast list
> to a small set of volunteers.

What is a “broadcast list”?

**Comment by gvwilson** [comment]
Mail is forwarded to a small set of people, but replies aren't allowed.

**Comment by wking** [comment]
On Tue, Apr 21, 2015 at 03:22:53PM -0700, Greg Wilson wrote:
> Mail is forwarded to a small set of people, but replies aren't
> allowed.

Why block replies?  Isn't that going to lead to things like:

  Alice→all: Can someone help me with …?
  Bob→Alice: Sure, tell me more about ….
  Charlie→Alice: Absolutely, tell me more about ….
  Dave→Alice: Yeah, tell me more about ….
  Erin→Alice: No problem, tell me more about ….

which Alice might not find particularly helpful ;).

I don't see a downside to allowing replies, because:

1. Some issues can be solved completely in the first follow up email.
2. Many issues are going to come up several times, and it's good to
   have a public record in the list, so you can say “Hi Eve!  We just
   went through that same issue with Alice last week.  See {Gmane
   link}, and let us know if you still have any questions”.
3. The only long-term subscribers to the list are likely going to be
   the help-providers, and:
   a. They'll likely want to know how other help-providers are
      handling questions, who's handling which questions, etc.
   b. They'll likely have sophisticated-enough mail-handling tools
      that they aren't overwhelmed by a few extra replies.

To avoid swamping the help-askers in replies, I'd recommend they not
subscribe up for the list, and instead just post to it (with a
moderator gatekeeping to avoid spam).  Then my example exchange
becomes:

  Alice→helpers: Can someone help me with …?
  Bob→(Alice and helpers): Sure, tell me more about ….

after which Charlie, Dave, … would know that Alice is being helped and
only follow the thread if they were interested in helping Bob help
Alice, or in seeing Bob's mad helping skills to improve their own
practice ;).
