### ISSUE TITLE
Build tool to push shell history to Etherpad

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/site#955]
Started in http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-April/002960.html

**Comment by chendaniely** [comment]
API Documentation: https://github.com/ether/etherpad-lite/wiki/HTTP-API

**Comment by wking** [comment]
Previous work by Mike Jackson here [1] (he also links to my earlier
script-publish.py post [2] and a few similar discussions).  Wiring
either approach up to Etherpad's API (I assume it has one ;) shouldn't
be too difficult.

[1]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2014-July/001902.html
[2]: http://lists.software-carpentry.org/pipermail/tutors_lists.software-carpentry.org/2013-January/000545.html

**Comment by douglatornell** [comment]
This is perhaps slightly off topic, but related, I think.

I have used the following incantation to push instructors' command-line history line-by-line to a web page that the learners could access:

```bash
HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S $ "
PROMPT_COMMAND="history 1 >> ~/history.txt; rsync -qz ~/history.txt sable:public_html/swc/2014-09-25-ubc/history.txt"
```

The first line sets the appearance of the command prompt in the history so that lines in the file on the server look like:

```bash
  758  2014-09-26 16:00:13 $ hg stat
```

The second line sets a command to execute a command after each command-line input. The command does 2 things:

```bash
history 1 >> ~/history.txt
```

appends the most recent command to the `~/history.txt file`, and

```bash
rsync -qz ~/history.txt sable:public_html/swc/2014-09-25-ubc/history.txt
```

uses` rsync` to push the addition to `~/history.txt` to a `public_html/` file. Substitute your own server and public web space location.

`HISTTIMEFORMAT` and `PROMPT_COMMAND` are shell variables, so they need to be set in each new shell session. I automated setting and unsetting them via bash functions on both my laptop and that of my co-instructor's so that we could pass back and forth whose command history was being synced to the web page.

This setup assumes that you are on a network remote to the one that your web server is on so you don't have direct access to your `~/public_html/` (or whatever) directory. If you do have direct access there you can leave off the `rsync` and just do something like:

```bash
history 1 >> ~/public_html/history.txt
```

On a remote network you need to have ssh keys and an ssh-agent set up between your laptop and the machine that you `rsync` to.

In the workshop where we used this the instructors did edits to the file on the server after their teaching sections to add context. Not as easy or distributed as Etherpad, but not far off.
